---

- hosts: 127.0.0.1
  vars_files:
   - ./default_vars.yml
   - ../config.yml
  roles:
    - { role: kamaln7.swapfile, swapfile_size: "{{ vm_swapsize }}" }
  tasks:
    - name: network config (ip_forward)
      sysctl: name="net.ipv4.ip_forward" value=1 sysctl_set=yes state=present reload=yes
    
    - name: add iptable rule
      command: /sbin/iptables -t nat -A POSTROUTING -o eth1 -j MASQUERADE
      sudo: true
  
    - name: save iptables
      command: iptables-save
      sudo: true
 
    - name: restart iptables
      service: name=ufw state=restarted
      sudo: true
  
    - name: install git
      apt: "name=git update_cache=yes"
      sudo: True
                  
    - name: git config https instead git
      command: git config --global url."https://".insteadOf git://
      sudo: True

    - name: checkout devstack
      git: "repo={{ git_base }}/openstack-dev/devstack.git dest=/opt/stack/devstack version={{ branch_version }}"

    - name: checkout trove-integration
      git: "repo={{ git_base }}/openstack/trove-integration.git dest=/opt/stack/trove-integration version=master"
      when: trove

    - name: checkout diskimage-builder
      git: "repo={{ git_base }}/openstack/diskimage-builder.git dest=/opt/stack/diskimage-builder version=master"
      when: trove
    
    - name: checkout tripleo
      git: "repo={{ git_base }}/openstack/tripleo-image-elements.git dest=/opt/stack/tripleo-image-elements version=master"
      when: trove

    - name: checkout designate
      git: "repo={{ git_base }}/openstack/designate.git dest=/opt/stack/designate version={{ branch_version }}"
      when: designate

    - name: install designate extension
      command: bash -c 'cd /opt/stack/devstack; /opt/stack/designate/contrib/devstack/install.sh'
      when: designate

    - name: remove localrc
      file: path=/opt/stack/devstack/localrc state=absent
      
    - name: local.conf
      template: src=local.conf.j2 dest=/opt/stack/devstack/local.conf
 
    - name: launchredstack
      template: src=launchredstack.sh.j2 dest=/opt/stack/launchredstack.sh
      when: trove
  
    - name: rsync trove-integration
      synchronize: src=/opt/stack/trove-integration dest=/opt/stack/tiwork
      when: trove
    
    - name: ubuntu user
      user: name=ubuntu state=present
      when: trove
      
    - name: add public key
      authorized_key: user=ubuntu key="{{ lookup('file','/opt/stack/tiwork/trove-integration/scripts/files/keys/id_rsa.pub') }}" state=present
      when: trove
      
    - name: i386 building
      replace: dest=/opt/stack/tiwork/trove-integration/scripts/functions_qemu regexp=amd64 replace=i386
      when: trove and vm_archbits == 32
      
    - name: add no-tmpfs
      replace: dest=/opt/stack/tiwork/trove-integration/scripts/functions_qemu regexp='disk-image-create -a' replace='disk-image-create --no-tmpfs -a'
      when: trove and vm_memory < 4096
    
    - name: replace password
      replace: dest=/opt/stack/tiwork/trove-integration/scripts/redstack.rc regexp='_PASSWORD=.*$' replace='_PASSWORD=openstack'
      when: trove
      
    - name: replace token
      replace: dest=/opt/stack/tiwork/trove-integration/scripts/redstack.rc regexp='SERVICE_TOKEN=.*$' replace='SERVICE_TOKEN=tokentoken'
      when: trove     
   
    - name: replace swift-hash
      replace: dest=/opt/stack/tiwork/trove-integration/scripts/redstack.rc regexp='SWIFT_HASH=.*$' replace='SWIFT_HASH=tokentoken'
      when: trove      
    
    - name: replace keys.gnupg.net
      replace: dest=/opt/stack/tiwork/trove-integration/scripts/files/elements/ubuntu-percona/pre-install.d/10-percona-apt-key regexp='hkp://keys.gnupg.net' replace='pool.sks-keyservers.net' 
      replace: dest=/opt/stack/tiwork/trove-integration/scripts/files/elements/ubuntu-mysql/pre-install.d/10-percona-apt-key  regexp='hkp://keys.gnupg.net' replace='pool.sks-keyservers.net'
      replace: dest=/opt/stack/tiwork/trove-integration/scripts/files/elements/ubuntu-percona/pre-install.d/10-percona-apt-key  regexp='hkp://keys.gnupg.net' replace='pool.sks-keyservers.net'
      replace: dest=/opt/stack/tiwork/trove-integration/scripts/files/elements/ubuntu-mysql/pre-install.d/10-percona-apt-key  regexp='hkp://keys.gnupg.net' replace='pool.sks-keyservers.net'
      when: trove      
    
    - name: install python-pip
      apt: "name=python-pip update_cache=yes"
      sudo: True
      when: trove

    - name: install dib-utils
      command: pip install dib-utils
      sudo: True
      when: trove
    
    
